'use client';
import {useEffect,useState} from 'react';
import initial from './initial-menus.json';
import {menuDish,type Language} from './menu-language';
type Restaurant={name:string;url:string;menu_url?:string;days:string[][];week?:number|null;year?:number|null;price?:string|null;coffeeIncluded?:boolean;originalLanguage?:string;days_en?:(string|null)[][];days_sv?:(string|null)[][];date_label?:string|null;permanent?:boolean;status?:string;error?:string|null;fetched?:string;fetchMs?:number};
type MenuData={restaurants:Restaurant[];errors:{name:string;detail:string}[];updated?:string|null;serviceError?:string;refreshing?:boolean};
const weekdays={sv:['Måndag','Tisdag','Onsdag','Torsdag','Fredag'],en:['Monday','Tuesday','Wednesday','Thursday','Friday']};
function currentDate(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Europe/Stockholm'}));}
function weekOf(date:Date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));return {year:d.getUTCFullYear(),week:Math.ceil(((+d-+new Date(Date.UTC(d.getUTCFullYear(),0,1)))/86400000+1)/7)};}
function stamp(s:string|null|undefined,language:Language){return s?new Date(s).toLocaleString(language==='sv'?'sv-SE':'en-GB',{timeZone:'Europe/Stockholm'}):language==='sv'?'Aldrig':'Never';}
function displayPrice(value:string,language:Language){value=value.replace(/^(?:Dagens\s+lunch|Lunch)\s+/i,'');return language==='sv'?value.replace(/Early bird/g,'Tidig lunch').replace(/Lunch card/g,'Lunchkort').replace(/Eatery card/g,'Eatery-kort').replace(/10% off/g,'10% rabatt'):value.replace(/Dagens lunch/gi,'Lunch');}
function safeUrl(s?:string){return /^https?:\/\//i.test(s||'')?s:'#';}
export default function Home(){
 const [data,setData]=useState<MenuData>(initial as MenuData),[day,setDay]=useState(0),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [language,setLanguage]=useState<Language>('sv'),[translations,setTranslations]=useState<Record<string,string>>({}),[translating,setTranslating]=useState(false);
 const t=(sv:string,en:string)=>language==='sv'?sv:en;
 const names=weekdays[language];
 const sourceError=(detail:string)=>{const http=detail.match(/HTTP\s*\d+/i)?.[0];return http?t('Restaurangens webbplats svarade med ','The restaurant website returned ')+http:t('Menyn kunde inte hämtas. Försök igen senare.','The menu could not be fetched. Please try again later.');};
 const [current,setCurrent]=useState(weekOf(new Date(initial.updated)));
 async function load(force=false){setBusy(true);setError('');try{const [r,tr]=await Promise.all([fetch('./menus.json',{cache:'no-store'}),fetch('./translations.json',{cache:'no-store'})]);if(!r.ok)throw Error('Unavailable');setData(await r.json());if(tr.ok)setTranslations(await tr.json());}catch{setError('unavailable');}finally{setBusy(false);}}
 useEffect(()=>{const now=currentDate();setDay(Math.min(Math.max(now.getDay()-1,0),4));setCurrent(weekOf(now));void load();},[]);
 useEffect(()=>{try{const saved=localStorage.getItem('lundlunch-language');if(saved==='en'||saved==='sv')setLanguage(saved);}catch{}},[]);
 useEffect(()=>{document.documentElement.lang=language;},[language]);
 function chooseLanguage(next:Language){setLanguage(next);try{localStorage.setItem('lundlunch-language',next);}catch{}}
 const sortedRestaurants=[...data.restaurants].sort((a,b)=>a.name.localeCompare(b.name,'sv',{sensitivity:'base'}));
 const rows=sortedRestaurants.filter(r=>(r.name+' '+(r.days[day]||[]).join(' ')+' '+(r.days[day]||[]).map((_,i)=>menuDish(r,day,i,language,translations).text).join(' ')).toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 function saveDiagnostics(){const value={updated:data.updated,errors:data.errors,restaurants:data.restaurants.map(r=>({name:r.name,url:r.url,status:r.status,fetched:r.fetched,error:r.error,fetchMs:r.fetchMs}))};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='lund-lunch-status.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <main><header><h1>Lund Lunch</h1><div className="header-actions"><div className="language-switch" role="group" aria-label={t('Menyspråk','Menu language')}><button className={language==='sv'?'active':''} aria-pressed={language==='sv'} onClick={()=>chooseLanguage('sv')}>Svenska</button><button className={language==='en'?'active':''} aria-pressed={language==='en'} onClick={()=>chooseLanguage('en')}>English</button></div><button onClick={()=>load(true)} disabled={busy}>{busy?t('Uppdaterar…','Refreshing…'):t('Läs in menyer igen','Reload menus')}</button></div></header>
 <p className="status" aria-live="polite">{t('Vecka','Week')} {current.week}, {current.year} · {busy?t('Läser in menyer…','Loading menus…'):t('Senast kontrollerat: ','Last checked: ')+stamp(data.updated,language)}{data.refreshing?t(' · En uppdatering pågår.',' · An update is in progress.'):''}</p>
 {(error||data.serviceError)&&<p className="warn" role="status">{error?t('Menyerna kunde inte hämtas. Försök igen.','The menus could not be loaded. Please try again.'):t('Liveuppdateringar är tillfälligt otillgängliga. Visar senast sparade menyer.','Live updates are temporarily unavailable. Showing the last saved menus.')}</p>}
 <nav aria-label={t('Välj veckodag','Choose weekday')}>{names.map((name,i)=><button key={name} className={day===i?'active':''} aria-pressed={day===i} onClick={()=>setDay(i)}>{name}</button>)}</nav>
 <input type="search" aria-label={t('Sök restauranger eller rätter','Search restaurants or dishes')} placeholder={t('Sök restauranger eller rätter, t.ex. kyckling, fisk, Troppo','Search restaurants or dishes, e.g. chicken, fish, Troppo')} value={query} onChange={e=>setQuery(e.target.value)}/>
 <table className="menus" aria-label={`${names[day]} ${t('lunchmenyer','lunch menus')}`}><tbody>{rows.map(r=>{
 const selected=(r.days[day]||[]).map((_,i)=>menuDish(r,day,i,language,translations)),dishes=selected.map(d=>d.text),warnings=[];
 const missing=selected.some(d=>d.missing);
 if(r.status==='cached')warnings.push(t('Senaste uppdateringen misslyckades. Visar senast sparade meny.','Latest refresh failed. Showing the last saved menu.'));
 if(r.status==='unavailable')warnings.push(t('Menyn är inte tillgänglig. Se Källstatus nedan.','Menu unavailable. See Source status below.'));
 if(r.week&&(r.week!==current.week||(r.year&&r.year!==current.year)))warnings.push(t('Publicerad meny: vecka ','Published menu: week ')+r.week+(r.year?', '+r.year:'')+t('. Kontrollera datumen.','. Please check the dates.'));
 if(r.status!=='unavailable'&&!r.week&&!r.permanent)warnings.push(t('Menydatum anges inte på restaurangens webbplats.','Menu dates are not labelled on the restaurant website.'));
 const list=<ul lang={language}>{dishes.map((s,i)=><li key={i} lang={selected[i].missing?(r.originalLanguage||'sv'):language}>{s}</li>)}</ul>;
 return <tr key={r.name}><th scope="row"><a href={safeUrl(r.url)} target="_blank" rel="noopener noreferrer">{r.name}</a>{r.price&&<div className="price">{displayPrice(r.price,language)}</div>}{r.coffeeIncluded&&<div className="price">{t('ink. Kaffe','incl. coffee')}</div>}</th><td>{missing&&<p className="translation-note" aria-live="polite">{translating?t('Översätter…','Translating…'):t('Översättningen är inte tillgänglig. Visar originaltext.','Translation unavailable. Showing original text.')}</p>}{warnings.map(w=><p className="warn" key={w}>{w}</p>)}{!dishes.length?<p>{t('Ingen läsbar meny för denna dag.','No readable menu for this day.')}</p>:r.permanent&&dishes.length>6?<details><summary>{dishes.length} {t('sallader, bowls och wraps','salads, bowls and wraps')}</summary>{list}</details>:list}</td></tr>;
 })}{!rows.length&&<tr><td colSpan={2}>{t('Inga restauranger eller rätter matchar sökningen.','No matching restaurants or dishes.')}</td></tr>}</tbody></table>
 <details className="sources"><summary>{t('Källstatus','Source status')}</summary><div className="source-scroll"><table aria-label={t('Status för menykällor','Menu source status')}><thead><tr><th>{t('Restaurang','Restaurant')}</th><th>Status</th><th>{t('Meny','Menu')}</th><th>{t('Senast hämtad','Last successful fetch')}</th><th>{t('Källa','Source')}</th></tr></thead><tbody>{sortedRestaurants.map(r=><tr key={r.name}><th scope="row">{r.name}</th><td>{r.status==='live'?t('Hämtad','Fetched successfully'):r.status==='cached'?t('Sparad meny · uppdatering misslyckades','Saved menu · refresh failed'):t('Menyn är inte tillgänglig','Menu unavailable')}</td><td>{r.permanent?t('Ordinarie meny','Regular menu'):r.week?t('Vecka ','Week ')+r.week+(r.year?', '+r.year:''):t('Inte angivet','Not labelled')}</td><td>{stamp(r.fetched,language)}</td><td><a href={safeUrl(r.menu_url||r.url)} target="_blank" rel="noopener noreferrer">{t('Officiell meny','Official menu')}</a></td></tr>)}</tbody></table></div>{data.errors.length>0&&<div className="error-list">{data.errors.map(e=><p key={e.name}><strong>{e.name}:</strong> {sourceError(e.detail)}</p>)}</div>}<button onClick={saveDiagnostics}>{t('Spara felsökningsinformation','Save diagnostics')}</button></details>
 <footer>{t('Menyerna hämtas direkt från restaurangerna och deras officiella menytjänster. Priser och utbud kan ändras.','Menus come directly from the restaurants and their official menu providers. Prices and availability may change.')}<br/>{t('Menyerna kontrolleras automatiskt på vardagsmorgnar och flera gånger på måndagar. Knappen läser in den senaste sparade versionen. Svensk tid gäller.','Menus are checked automatically on weekday mornings and several times on Mondays. The button reloads the latest saved version. Swedish time applies.')}</footer>
 </main>;
}
