import restaurants from './restaurants.json' with {type:'json'};
import entities from './entities.json' with {type:'json'};
export {restaurants};
const DAYS=['Måndag','Tisdag','Onsdag','Torsdag','Fredag'];
export function stockholmDate(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Europe/Stockholm'}));}
export function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));return {year:d.getUTCFullYear(),week:Math.ceil(((d-new Date(Date.UTC(d.getUTCFullYear(),0,1)))/86400000+1)/7)};}
export function lines(raw){
 return raw.replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style|noscript)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,'')
 .replace(/<\/?(?:p|div|h[1-6]|li|br|tr)\b[^>]*>/gi,'\n').replace(/<[^>]*>/g,'')
 .replace(/&(#x[\da-f]+|#\d+|[a-z][\da-z]+);/gi,(all,key)=>{if(key[0]==='#'){const n=key[1].toLowerCase()==='x'?parseInt(key.slice(2),16):parseInt(key.slice(1),10);return n<=0x10ffff?String.fromCodePoint(n):all;}return entities[key]??all;})
 .replace(/[\u200d\u200b]/g,'').split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean);
}
export async function fetchPage(url){let error;for(const agent of ['LundLunch/1.0 (personal lunch menu reader)','Mozilla/5.0']){try{const r=await fetch(url,{headers:{'User-Agent':agent,'Accept':'text/html,application/json,*/*','Accept-Language':'sv,en;q=0.9'},signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error(`HTTP ${r.status}: ${r.statusText}`);const text=await r.text();if(text.length>4000000)throw Error('Menu page is too large.');return text;}catch(e){error=e;}}throw error;}
function heading(s){return DAYS.findIndex(d=>new RegExp('^'+d+'(?:$|\\s*[:/,]|\\s+\\d|\\s+[–-])','i').test(s));}
function price(s){return /^(?:Dagens lunch\s+|Lunch\s+)?\d+(?:[-/]\d+)?\s*(?:kr|:-)(?:\s+ink\..*)?$/i.test(s);}
function sections(ls,stop){const ds=DAYS.map(()=>[]);let current=-1;for(const s of ls){const hit=heading(s);if(hit>=0){current=hit;ds[hit]=[];continue;}if(current<0)continue;if(stop.test(s))break;if(!price(s))ds[current].push(s);}return ds;}
function metadata(ls){const text=ls.join(' '),match=text.match(/(?:\bvecka\s*|\bweek\s*|\bv\.?\s*)(\d{1,2})\b/i),ym=text.match(/\b(?:week|vecka)\s*\d{1,2}\s*[,/]?\s*(20\d{2})\b/i);let week=match?Number(match[1]):null,year=ym?Number(ym[1]):null,date_label=null;
 const dm=text.match(/\bMeny\s+(\d{1,2})\/(\d{1,2})\s*[–-]\s*(\d{1,2})\/(\d{1,2})/i);if(dm){date_label=dm[0];const d=new Date(Date.UTC(stockholmDate().getFullYear(),+dm[2]-1,+dm[1]));if(d.getUTCDay()===1)week=isoWeek(d).week;}
 if(!week){const dm=text.match(/\bMåndag\s*,?\s*(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Maj|Jun|Jul|Aug|Sep|Oct|Okt|Nov|Dec)\b/i);if(dm){const months={jan:0,feb:1,mar:2,apr:3,may:4,maj:4,jun:5,jul:6,aug:7,sep:8,oct:9,okt:9,nov:10,dec:11};date_label=dm[0];const d=new Date(Date.UTC(stockholmDate().getFullYear(),months[dm[2].toLowerCase()],+dm[1]));if(d.getUTCDay()===1)week=isoWeek(d).week;}}
 return {week,year,date_label};}
function categories(day,inline=false){const dishes=[];let cat=null;for(const s of day){if(inline){if(/^(Green|Local|World|Asia)\s*\|/i.test(s)||!dishes.length)dishes.push(s);else dishes[dishes.length-1]+=' '+s;}else if(/^(Green|Local|World\s*wide|Pizza|Äppelpaj)$/i.test(s)){cat=s;}else{dishes.push((cat?cat+': ':'')+s);cat=null;}}return dishes;}
// Menu language cues, independent of markup, typeface and translation order.
export function englishDish(s){
 const words=s.toLowerCase().match(/[a-zåäö]+/g)||[];
 const english=new Set('beef stew parsnip cucumber cauliflower crouqette croquette jerusalem artichoke lentils mince minced patties lingon berries creamed gravy chickpea pancake goats cheese swedish hash beetroot egg noodles bamboo herring butter veggie burger gherkin chicken red curry rosemary pork veal lamb fish salmon cod haddock potato potatoes mashed roasted baked fried grilled rice vegetables peas beans carrots cream sauce mushroom mushrooms onion onions garlic leek leeks cabbage dill meatballs served with and'.split(' '));
 const swedish=new Set('dillkött palsternacka pressgurka blomkålskrokett jordärtskocka linser pannbiff lingon gräddsås kikärtspannkaka getost pytt bellman rödbetor ägg nudlar bambu strömming smör vegburgare saltgurka kyckling röd rosmarin nötkött fläsk kalv lamm fisk lax torsk potatis potatismos rostad rostade bakad stekt grillad ris grönsaker ärtor bönor morötter grädde sås svamp lök vitlök purjolök kål köttbullar med och'.split(' '));
 const en=words.filter(w=>english.has(w)).length,sv=words.filter(w=>swedish.has(w)||/[åäö]/.test(w)).length;
 return en>sv;
}
export function lokalEnglish(raw,days){
 const bilingual=sections(lines(raw),/^Dagens lunch/i);
 return days.map((day,i)=>day.map(s=>{
  const source=bilingual[i],at=source.indexOf(s);if(at<0)return null;
  const translated=[];for(const line of source.slice(at+1)){if(!englishDish(line))break;translated.push(line);}
  return translated.length?(/^Veg:/i.test(s)?'Veg: ':'')+translated.join(' '):null;
 }));
}
export function parseMenu(c,raw){const kind=c.parser,ls=lines(raw),meta=metadata(ls);let ds=DAYS.map(()=>[]);const permanent=kind==='salads';
 if(kind==='troppo'){const start=ls.findIndex(s=>s.toLowerCase()==='monday-friday');if(start<0)throw Error('Menu heading not found.');const dishes=[];let chunk=[];for(const s of ls.slice(start+1)){if(s.toLowerCase()==='find us')break;if(s.toLowerCase().startsWith('enjoy your lunch'))continue;if(s.toLowerCase()==='or'){if(chunk.length)dishes.push(chunk.join(' '));chunk=[];}else chunk.push(s);}if(chunk.length)dishes.push(chunk.join(' '));ds=DAYS.map(()=>[...dishes]);}
 else if(kind==='salads'){const start=ls.findIndex(s=>s.startsWith('HERBAL HUMMUS')),end=ls.findIndex(s=>s.startsWith('PASSION APPLE'));if(start<0||end<0)throw Error('Regular menu entries not found.');const dishes=[];let chunk=[];for(const s of ls.slice(start,end)){if(s.includes('Allergi & Näringsinfo')||s.startsWith('Mejla oss'))continue;chunk.push(s);if(price(s)){dishes.push(chunk.join(' '));chunk=[];}}ds=DAYS.map(()=>[...dishes]);meta.week=null;meta.year=null;}
 else if(kind==='matstudio'){ds=sections(ls,/^(Veckans gröda|Alla rätter|Varmt välkomna|A LA CARTE)/i);const start=ls.findIndex(s=>s.startsWith('Veckans gröda')),weekly=[];if(start>=0)for(const s of ls.slice(start+1)){if(/^(Alla rätter|Varmt välkomna|A LA CARTE)/i.test(s))break;weekly.push(s);}ds=ds.map(d=>[...(d.length?[d.join(' ')]:[]),...(weekly.length?['Veckans gröda: '+weekly.join(' ')]:[])]);}
 else if(kind==='kantin'){ds=sections(ls,/^Hitta till kantin/i);const weekly=[];for(const label of ['Veckans vegetariska:','Månadens alternativ:']){const i=ls.findIndex(s=>s.startsWith(label));if(i>=0&&i+1<ls.length)weekly.push(label+' '+ls[i+1]);}ds=ds.map(d=>[...(d.length?[d.join(' ')]:[]),...weekly]);}
 else{const bounds={lokal:/^Dagens lunch/i,bryggan:/^(Med reservation|För allergener)/i,bricks:/^VÅRA ÖPPETTIDER/i,edison:/^(SE LUNCHMENYN|Öppettider)/i,inspira:/^Konferens/i,hojd:/^DUMPLINGS/i};ds=sections(ls,bounds[kind]||/^Öppettider/i);if(['bricks','edison'].includes(kind))ds=ds.map(d=>categories(d));else if(kind==='inspira')ds=ds.map(d=>categories(d,true));else if(kind==='lokal'){ds=ds.map(d=>d.filter(s=>!englishDish(s)));for(const d of ds)for(let i=d.length-1;i>0;i--)if(!/[–—-]|^Veg:/.test(d[i])&&!d[i-1].startsWith('Veg:')){d[i-1]+=' '+d[i];d.splice(i,1);}}else if(kind==='hojd')ds=ds.map(d=>d.flatMap(s=>s.split(/(?=\b\d+\.\s)/).map(dish=>dish.trim()).filter(Boolean)));}
 if(!ds.some(d=>d.length))throw Error('No readable dishes found. The restaurant page may have changed.');let amount=ls.find(price)||null;if(kind==='bryggan'){const text=ls.join(' '),regular=text.match(/Dagens rätt eller vegetariska\s*(\d+)\s*kr/i),card=text.match(/Med vårt lunchkort\s*(\d+)\s*kr/i),student=text.match(/Student\s*(\d+)\s*kr/i);amount=regular?regular[1]+' kr'+(card?' · Lunch card '+card[1]+' kr':'')+(student?' · Student '+student[1]+' kr':''):amount;}
 return {name:c.name,url:c.url,menu_url:c.menu_url||c.url,days:ds,...meta,permanent,originalLanguage:kind==='troppo'?'en':'sv',days_en:kind==='lokal'?lokalEnglish(raw,ds):undefined,coffeeIncluded:!!c.coffeeIncluded,price:permanent?null:amount?.replace(/\s+ink\.\s*Kaffe/i,''),source:'Restaurant website',status:'live',error:null};
}
function firestoreValue(v){if(v.mapValue)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,firestoreValue(x)]));if(v.arrayValue)return(v.arrayValue.values||[]).map(firestoreValue);for(const k of ['stringValue','booleanValue','integerValue','doubleValue','timestampValue','nullValue'])if(k in v)return v[k];return null;}
async function postJSON(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error(`Official menu service: HTTP ${r.status}`);return r.json();}
function recurring(rule,date){if(!rule)return true;const start=new Date(rule.startDate+'T00:00:00Z'),delta=(date-start)/86400000,interval=Math.max(1,Number(rule.interval||1))*7,key=date.toISOString().slice(0,10),count=Number(rule.count||0);return delta>=0&&delta%interval===0&&(!count||delta/interval+1<=count)&&(!rule.until||key<=rule.until)&&!(rule.exceptions||[]).includes(key);}
export function eateryPrice(raw){const text=lines(raw).join(' '),regular=text.match(/11[:.]00\s*[–-]\s*14[:.]00\s*\(ordinarie\)\s*(\d+)\s*kr/i),early=text.match(/11[:.]00\s*[–-]\s*11[:.]30\s*\(Early-bird\)\s*(\d+)\s*kr/i);if(!regular)throw Error('Eatery lunch price not found.');return regular[1]+' kr'+(early?' · Early bird '+early[1]+' kr (11:00–11:30)':'')+(/10\s*%\s*rabatt med Eatery-kortet/i.test(text)?' · Eatery card: 10% off':'');}
export async function loadEatery(c){const base='https://firestore.googleapis.com/v1/projects/pej-menu-display/databases/(default)/documents',query={structuredQuery:{from:[{collectionId:'organizations'}],select:{fields:[{fieldPath:'menus'}]},where:{fieldFilter:{field:{fieldPath:'slug'},op:'EQUAL',value:{stringValue:'ea'}}},limit:1}};
 const [rows,pricePage]=await Promise.all([postJSON(base+':runQuery',query),fetchPage(c.url)]),lunchPrice=eateryPrice(pricePage),doc=rows.find(r=>r.document)?.document;if(!doc)throw Error('Eatery organization not found.');const menu=(firestoreValue(doc.fields.menus)||[]).find(m=>m.slug==='lund');if(!menu)throw Error('Eatery Lund menu not found.');const now=stockholmDate(),mon=new Date(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()));mon.setUTCDate(mon.getUTCDate()-(mon.getUTCDay()+6)%7);const entries=menu.entries||{},all=[],closed=[];
 for(let i=0;i<5;i++){const date=new Date(+mon+i*86400000),key=date.toISOString().slice(0,10),entry=entries[key]||{};closed.push(['closed','temporary closed','temporarily closed'].includes(String(entry.status||'').toLowerCase()));const blocks=(entry.informationBlocks||[]).filter(b=>recurring(b.recurrence,date));for(const [otherKey,other] of Object.entries(entries))if(otherKey!==key)for(const block of other.informationBlocks||[])if(block.recurrence&&recurring(block.recurrence,date))blocks.push(block);const order=new Map((entry.order||[]).map((k,i)=>[k,i]));blocks.sort((a,b)=>(order.get(a.id)??order.size)-(order.get(b.id)??order.size));all.push(blocks);}
 const ids=[...new Set(all.flat().map(b=>b.libraryItemId).filter(Boolean))],library=new Map();if(ids.length){const rows=await postJSON(base+':batchGet',{documents:ids.map(id=>doc.name+'/items/'+id),mask:{fieldPaths:['name','description','status']}});for(const row of rows)if(row.found)library.set(row.found.name.split('/').pop(),Object.fromEntries(Object.entries(row.found.fields||{}).map(([k,v])=>[k,firestoreValue(v)])));}
 const text=(v,language)=>typeof v==='string'?(language==='sv'?v:''):v?.[language]||'';
 const render=(language)=>all.map((blocks,i)=>closed[i]?[language==='sv'?'Stängt':'Closed']:blocks.flatMap(b=>{
  const item=b.libraryItemId?library.get(b.libraryItemId):b;if(!item||['hidden','archived'].includes(item.status)||['hidden','archived'].includes(b.status))return [];
  const name=text(item.name,language),desc=text(item.description,language);
  if(language==='en'&&((text(item.name,'sv')&&!name)||(text(item.description,'sv')&&!desc)))return [null];
  const dish=name+(name&&desc?' — ':'')+desc;return dish?[dish+([item.status,b.status].includes('temporarySoldOut')?(language==='sv'?' (Slutsåld)':' (Sold out)'):'')]:language==='en'?[null]:[];
 }));
 const days=render('sv'),days_en=render('en');if(!days.some(d=>d.length))throw Error('Eatery has not published this week’s menu.');
 return {name:c.name,url:c.url,menu_url:c.menu_url,days,days_en,originalLanguage:'sv',...isoWeek(mon),price:lunchPrice,coffeeIncluded:!!c.coffeeIncluded,permanent:false,source:'Official Pej menu',status:'live',error:null};
}
export async function refreshMenus(previous){const byName=new Map(previous.restaurants.map(r=>[r.name,r]));const errors=[];const rows=await Promise.all(restaurants.map(async c=>{const started=Date.now();try{const r=c.parser==='eatery'?await loadEatery(c):parseMenu(c,await fetchPage(c.menu_url||c.url));const fetchMs=Date.now()-started;console.info('Menu source timing',JSON.stringify({restaurant:c.name,fetchMs,status:'live'}));return {...r,fetched:new Date().toISOString(),fetchMs};}catch(e){const fetchMs=Date.now()-started;console.info('Menu source timing',JSON.stringify({restaurant:c.name,fetchMs,status:'cached',error:e?.message||String(e)}));const detail=e?.message||String(e);errors.push({name:c.name,detail});const old=byName.get(c.name);return old?{...old,status:'cached',error:detail,fetchMs}:{name:c.name,url:c.url,menu_url:c.menu_url||c.url,days:DAYS.map(()=>[]),week:null,status:'unavailable',error:detail,fetchMs};}}));return {version:11,restaurants:rows,errors,updated:new Date().toISOString()};}
